export const InvoiceData = {
  product: [
    {
      id: 1,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 2,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 3,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 4,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 5,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 6,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 7,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 8,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 9,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 10,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 11,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 12,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 13,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 14,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 15,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 16,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 17,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 18,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 19,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 20,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 21,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 22,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 23,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 24,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 25,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 26,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 27,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 28,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 29,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 30,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 31,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 32,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 33,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 34,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 35,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 101,
      name: "product name",
      discription: "Discription  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 102,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 36,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 37,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 38,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 39,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 40,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 41,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 42,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 43,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 44,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 45,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 46,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 47,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 48,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 49,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 50,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 51,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 52,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 53,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 54,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 55,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 56,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 57,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 58,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 59,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 60,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 61,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 62,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 63,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 64,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 65,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 66,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 67,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 68,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 69,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 70,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 71,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 72,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 73,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 74,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 75,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 76,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 77,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 78,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 79,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 80,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 81,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 82,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 83,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 84,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 85,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 86,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 87,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 88,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 89,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 90,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 91,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 92,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 93,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 94,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 95,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 96,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 97,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 98,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 99,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
    {
      id: 100,
      name: "product name",
      discription: "Discriptio wwwwwwwwwn  of  the Image ",
      quantity: "22",
      rate: 32,
      amount: 2323,
    },
  ],
};
